#version 450

layout(std140, set = 0, binding = 0) buffer VertexPositionsSSBO
{
	vec4 vertexPositions[];
};
layout(std140, set = 0, binding = 1) buffer VertexNormalsSSBO
{
	vec4 vertexNormals[];
};

struct PbdPositions
{
	vec3 predict;
    vec3 delta;
};

layout(std140, set = 0, binding = 2) buffer PositionsSSBO
{
	PbdPositions positions[];
};

layout(local_size_x = 1) in;

void main()
{
	uint index = gl_GlobalInvocationID.x;
	vertexPositions[index] = vec4(positions[index].predict, 0.0);
}