#version 450

layout(std140, set = 0, binding = 0) buffer VertexPositionsSSBO
{
	vec4 vertexPositions[];
};
layout(std140, set = 0, binding = 1) buffer VertexNormalsSSBO
{
	vec4 vertexNormals[];
};

layout(std140, set = 0, binding = 2) buffer TetPositionsSSBO
{
	vec4 tetpositions[];
};

layout(local_size_x = 1) in;

void main()
{
	uint index = gl_GlobalInvocationID.x;
	vertexPositions[index] = tetpositions[index];
}